### ISSUE TITLE
Opening a new TUI window for each opened file

### ISSUE THREAD

**Issue by nostdm** [mhinz/neovim-remote#107]
Hello, I just found this project and it seems really interesting. 

Whenever I run `nvr file.txt` it opens the file in an existing TUI interface, what I would like to happen is for `nvr` to spawn a new TUI but connect to the same nvim server, so that I can have multiple nvim windows open which are all connected to the same nvim server and share the same state. Is this possible with the current `nvim` TUI implementation to spawn a detached TUI process that talks to the same nvim server or is the nvim UI and server coupled together so that it can't be started separately?

**Comment by mhinz** [comment]
That's not possible yet, but there's a GSoC proposal for this exact thing: https://github.com/neovim/neovim/wiki/GSoC-2019-Ideas#tui-terminal-ui-remote-attachment

But as far as I know, no one works at that project at the moment.

Since this is nothing I can act on on, I'm closing this, but keep it in mind if proper TUI clients ever get implemented.

Thanks for the proposal!
