### ISSUE TITLE
nvr does no take NVIM_LISTEN_ADDRESS into account

### ISSUE THREAD

**Issue by jarkkojs** [mhinz/neovim-remote#152]
I've ended up for the sake of robustness to do

```
function nvr-connect {
  export socket=`find /tmp -maxdepth 1 -name "nvim*" | head -1`
 
  if [ -z "$socket" ]; then
    echo "NeoVim is not running."
  else
    export NVIM_LISTEN_ADDRESS=$socket
  fi
}
```

I like this over the global name because this will always work even if NeoVim was started with a variable socket name.

But when I use as below, nvr does not respect the environment variable:

```
~ master
❯ nvr-connect 

~ master
❯ echo $NVIM_LISTEN_ADDRESS
/tmp/nvimIaEski
```

I.e. it creates a new NeoVim instance instead of opening the file in $NVIM_LISTEN_ADDRESS pointed NeoVim.

**Comment by ysolis** [comment]
$NVIM_LISTEN_ADDRESS is deprecated in NeoVim

https://neovim.io/doc/user/deprecated.html

![image](https://user-images.githubusercontent.com/9123933/96664631-d6463400-1318-11eb-9f59-4f4f4b8377dd.png)

**Comment by seb-mueller** [comment]
Could that be updated in the Readme, since I had the same issues and spend quite a lot of time to get `nvr` working in neovim.
Also, even armed with that knowledge, it still can't get it to work in neovim, i.e.:
`nvim --listen /tmp/nvimsocket` followed by `:echo v:servername` gives me a temp file instead of nvimsocket (e.g. `/tmp/nvimgLlrnE/0`

**Comment by muratangin187** [comment]
Is there any solution?

**Comment by kylo252** [comment]
It seems to work fine if you just start neovim with `nvim --listen localhost` then you can use `nvr --servername localhost file1.txt`. You can also use `nvr --serverlist` to pull for all the available neovim servers.

**Comment by nyngwang** [comment]
> Could that be updated in the Readme, since I had the same issues and spend quite a lot of time to get `nvr` working in neovim. Also, even armed with that knowledge, it still can't get it to work in neovim, i.e.: `nvim --listen /tmp/nvimsocket` followed by `:echo v:servername` gives me a temp file instead of nvimsocket (e.g. `/tmp/nvimgLlrnE/0`

The same here!

**Comment by mhinz** [comment]
As of nvim 0.7, `nvim --listen foo` should be preferred over setting `$NVIM_LISTEN_ADDRESS` before starting `nvim`. The latter still works, but is considered obsolete.

Since people use it in scripts, nvr will continue supporting `$NVIM_LISTEN_ADDRESS`.

I'll update the README and the message given for `nvr --nostart` accordingly.
