### ISSUE TITLE
--serverlist differs from vim's output

### ISSUE THREAD

**Issue by DanielFGray** [mhinz/neovim-remote#18]
With `vim --serverlist` you can test whether there is a running instance of a vim server.

`nvr --serverlist` seems to always respond with `/tmp/nvimsocket` even if there's no running server.

I think it would be ideal that `nvr --serverlist` would emulate the previous behavior of `vim --serverlist` and not return anything if there are no running nvim sockets.

Testing whether the socket exists with something like `[[ -e /tmp/nvimsocket ]]` in bash is an easy workaround, but I can't help thinking it'd be nicer if `nvr` was a more faithful emulation of vim's clientserver functionality.

**Comment by mhinz** [comment]
Maybe `nvr -h` is a bit misworded here?

It's supposed to print the address to be used, which is always `/tmp/nvimsocket` if neither `$NVIM_LISTEN_ADDRESS` nor `--servername` set it to something else.

Opposed to Vim, there's no central instance that knows about all the clients; there's no way to make it work like in Vim.

**Comment by rafaqz** [comment]
This actually clobbers my workflow... I used to use vim like this:
- Open vim instances (always as servers) for various tasks 
- Open additional files from anywhere, at leasure, with --remote, using a script that would find the right vim instance from --serverlist based on the root dir.

That would be hard to do in nvim/nvr.

Couldn't all the vim instances be listed somewhere so that nvr --serverlist works and is actually a list rather than just one variable? It's pretty much a useless flag now. I'm imagining I would have to write a hack that echos the servernames to a file manually to be read later, but that would be too ugly.

**Comment by mhinz** [comment]
Every Neovim instance is a server on its own. But opposed to Vim, they don't know about each other. That's why it can't be done "nicely" from nvr.

Would a hacky oneliner work for your use case as well?

```
$ lsof -p $(pgrep nvim | paste -sd ',') | grep '\<unix\>' | awk '{ print $NF }' | sort
```

**Comment by DanielFGray** [comment]
this worked a bit better for me

``` sh
lsof -p $(command pgrep nvim | paste -sd ',') | awk '$5=="unix"' | grep -oP '/tmp/nvim[^\s]+'
```

**Comment by mhinz** [comment]
As of [this commit](https://github.com/mhinz/neovim-remote/commit/f78e3a9f0e4f9ffa396fc5418da1435a5c808bf3), `--serverlist` should behave as expected now.
