### ISSUE TITLE
Switch from term to file and back

### ISSUE THREAD

**Issue by hhsnopek** [mhinz/neovim-remote#24]
I noticed in the second gif that you switched from the term, opened the file, and then switched back to the term. How would one also achieve this functionality?

**Comment by mhinz** [comment]
See `nvr -h`. That's the `-l` option, that simply uses `:wincmd p` to switch to the previously accessed window before opening the files.

Obviously this only works when `nvr` is run from within `:terminal`. :-)

**Comment by hhsnopek** [comment]
Ahh thank you!! ❤️

**Comment by hhsnopek** [comment]
Hmm so I'm attempted to follow the same logic within the gif and can't recreate one part.

It looks like you enter the changelog in the current pane that held the terminal, with: `nvr CHANGELOG.md`. After that a shortcut must have been used to switch back to the term. 

This is the flow I'm looking for: Open File in current terminal pane, edit/save, return to terminal in that same pane

**Comment by mhinz** [comment]
You want everything to happen in the same window?

Well, terminal buffers are a bit special in some regards, but still buffers. So, after doing `nvr CHANGELOG`, you could simple write and delete that buffer with `:w | bd`, then it should switch back to the terminal buffer automatically. You just write and switch to the previous buffer with `:w | bp`.

If the problem is that your terminal buffers disappears after switching buffers, you might have to `:set hidden`.

**Comment by hhsnopek** [comment]
This is perfect, I need to read more into buffers. Thank you!!
