### ISSUE TITLE
use annotated tags

### ISSUE THREAD

**Issue by mmlb** [mhinz/neovim-remote#34]
All tags after v1.2.1 are lightweight tags and mess up use of bare `git describe` since according to git man pages lightweight tags are meant to be temporary.

I don't know the best way to fix tags that already exist since git will be silent on the mismatch (if you were to retag and push --force). Maybe a new (annotated tag)?

**Comment by mhinz** [comment]
> I don't know the best way to fix tags that already exist since git will be silent on the mismatch (if you were to retag and push --force). Maybe a new (annotated tag)?

Hmm, I'd like to avoid that.

Lightweight tags are easier to handle for this kind of repo, since I need to up the version for the Python package for every commit that changes the actual Python code (and not just the README).

Therefore there would be a lot of annotated tags with empty messages (since the "changelog" is simply the last commit message).

I don't know your use case, but `git describe --tags` seems to handle lightweight tags just fine.

**Comment by mmlb** [comment]
hmm yeah I fell back to using `--tags`, no biggie.
