### ISSUE TITLE
combine -o and --remote-wait

### ISSUE THREAD

**Issue by nhooyr** [mhinz/neovim-remote#35]
Currently, this is not possible, something like

```
nvr -o --remote-wait ~/code/somefile
```

gives

```
usage: /usr/local/bin/nvr [arguments]
nvr: error: argument -o: expected at least one argument
```

**Comment by mhinz** [comment]
1. `vim -o --remote-wait <file>` doesn't work as well. (Although it acts a bit different: it throws no error and ignores the `-o`).
1. It's documented that `-o` must take at least one argument.

I don't say it's impossible, but basically you want `-o` to take optional arguments and when no arguments are given act as a hint for `--remote-wait` to use `:split` instead of `:edit`.

So, I'd rather make it consistent with Vim and ignore the `-o` in that case.

But I guess that doesn't solve what you're trying to do, since `--remote-expr` is executed after `--remote-wait` on purpose. Should we introduce `--remote-split-wait` and friends?

**Comment by nhooyr** [comment]
I agree, the general option sounds better.

**Comment by mhinz** [comment]
Ehm, no idea why I was thinking of `--remote-expr-before`.. I meant the counterpart to `-c`. I called it `-cc`.

**Comment by mhinz** [comment]
`nvr -cc split --remote-wait <file>` should do what you want now.
