### ISSUE TITLE
Server list is empty in Windows

### ISSUE THREAD

**Issue by iamkarlson** [mhinz/neovim-remote#53]
Hi, I'm trying to make it work in Windows 10 but my server list is empty. I started neovim-qt and that is printout from v:servername:

```
\\.\pipe\nvim-18032-0
```

Could you help me how to attach nvr through this address?

**Comment by mhinz** [comment]
I have to admit that I never tested nvr with Windows.

Let me play around with it in the next days and report back.

**Comment by iamkarlson** [comment]
I've  set $NVIM_LISTEN_ADDRESS to ip4 but nvr is still unable to get server list

**Comment by mhinz** [comment]
I finally found some time to play around with Windows, but there were lots of problems..

[psutil](https://pythonhosted.org/psutil/) doesn't seem to support process connections on Windows. So `--serverlist` won't work.

And even if we find a way that doesn't use psutil, the [forking approach](https://github.com/mhinz/neovim-remote/blob/d138b98bdecf8e8f61c130dee0506db4af9edf77/nvr/nvr.py#L73-L89) won't work either, since Windows works fundamentally different.

Due to the above reasons, I decided no to support Windows. Sorry.
