### ISSUE TITLE
More documentation for remote-expr

### ISSUE THREAD

**Issue by snoblenet** [mhinz/neovim-remote#63]
Is it possible to get a bit more documentation on `remote-expr` please?

For example, I'm not sure why I'm getting:
```
➜  / nvr --remote-exp "checktime"
Evaluation failed: checktime
```

**Comment by mhinz** [comment]
In the output of `nvr -h`?

Commands came first (ancestry of vi) and the scripting language later, that's why Vim distinguishes between commands (starting with `:`) and expressions (like variables or functions; `:h expression`, `h function-list`).

So, in your case you want `nvr -c checktime` instead.

**Comment by snoblenet** [comment]
Beaut, thanks! Working for me now but the richer feedback may help others in the future.

(I'm writing a function to to send the ZSH mode to Neovim when running ZSH in a terminal in Neovim so I can have one consistent statusline.)

**Comment by mhinz** [comment]
Okay! Thanks for the feedback. I pushed v1.8.6 to PyPI.

**Comment by snoblenet** [comment]
Thanks for your previous help.
What if the command takes an argument?
I'm trying to do something like this in my `.zshrc`:
```
reload() {
 source ~/.zshrc
 tmux source-file ~/.tmux.conf
  # nvr -c source ~/.config/nvim/init.vim
}
```

**Comment by mhinz** [comment]
Put quotes around it to make zsh evaluate it as a single argument:

```sh
nvr -c 'source ~/.config/nvim/init.vim'
```

**Comment by snoblenet** [comment]
thanks
