### ISSUE TITLE
Opening lots of buffers slow

### ISSUE THREAD

**Issue by Alok** [mhinz/neovim-remote#71]
If I run ` touch {1..100} && nvr {1..100}`, it opens each file one by one, which takes a while and locks up the computer.

Doing it with actual files that have content in them takes forever.

Doing `nvim {1..100}` is practically instant and seems to open every buffer at the same time.

**Comment by mhinz** [comment]
When you do `nvim {1..100}`, it doesn't open 100 buffers, but only 1. You can test it with `:ls`. All but the current buffer will show the cursor position to be at line 0 and there's no `h` for "hidden" yet.

When you do `nvr {1..100}`, yes, each file will be opened one by one by telling the remote instance to use something like `:edit file1`, `:edit file2`, etc.

There's nothing I can do about that, but you could use something like `:h arglist`:

```
$ touch {1..100} && nvr -c 'args *'
```

Hope this helps.

**Comment by sharethewisdom** [comment]
Thanks for your work. The reason I now use nvr as `$EDITOR` in my tmux setup is to avoid opening and closing neovim, but in my `nvim --startuptime` measurements, opening buffers is always slowest. So imagine that it would be possible in the future that neovim would not need to read an entire file before loading contents into the buffer, like described in `less(1)`. 

So an iteration of the above question rather than an issue (sorry if it is inappropriate): would it be possible to parallelize opening multiple files? Would it be useful? Does this make sense? Could you expand on your solution with the arglist?

**Comment by mhinz** [comment]
Nvim, like Vim, currently slurps whole files into memory at once, yes. That's why editing big files is no fun.

Nvim intents to change that in the far, far future, but changing this most basic data structure (how file buffers are represented in memory) affects many subsystems and will be a hell of a change.

> would it be possible to parallelize opening multiple files? Would it be useful? Does this make sense?

I would say it's not worth to optimize for an uncommon case. If you need to load many files at once, `:args` is pretty useful, since, like mentioned above, it really just loads a single file at first.

If multiple files need to be opened via `:edit` in nvr, one could probably detect that and use `:args` instead. But do you really have an use case where you often load a load of files via `nvr`?

**Comment by mhinz** [comment]
Would be optimizing the `nvr file1 file2 ... file2000` case enough?

```diff
diff --git i/nvr/nvr.py w/nvr/nvr.py
index b19e5cf..80ffda6 100644
--- i/nvr/nvr.py
+++ w/nvr/nvr.py
@@ -434,7 +434,10 @@ def main(argv=sys.argv, env=os.environ):
             options.O = arguments
         else:
             # Act like --remote-silent by default.
-            nvr.execute(arguments, 'edit', silent=True)
+            # Optimization: Instead of :edit one file after the other,
+            # use :args and only load the first one into memory.
+            files = list(map(lambda f: nvr.server.funcs.fnameescape(os.path.abspath(f)), arguments))
+            nvr.server.command('silent args {}'.format(" ".join(files)))

     if options.remote_send:
         nvr.server.input(options.remote_send)
```

For not breaking backward compatibility it would need a few more changes, but you could test if this change results in the speed improvement you're hoping for.

**Comment by sharethewisdom** [comment]
I tried it and it does work, but even one file feels slow to me, plus, and I decided that I like tabs. 
thanks

It's probably better that I'll take another look at speed improvements by cleaning up the shada file, removing some plugins, etc.
