### ISSUE TITLE
Document workflow suggestions for :terminal, git commits, and nvr, a little better?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [mhinz/neovim-remote#96]
Switching to Neovim and `:terminal` has been really exciting for me, so far; and `nvr` is definitely going a long way towards helping with that!

There's also a few really helpful FAQs / suggestions in the README, which I appreciate quite a lot, as something of an eternal noob!

Unfortunately, I still can't really figure out how to make a *super-basic* workflow — one that seems like it should be obvious / default behaviour — work for me. I'm using the suggested `$VISUAL` config:

```viml
if has('nvim')
  let $VISUAL = 'nvr -cc split --remote-wait'
endif
```

… as well as having `nvr -s --remote-wait-silent` as my `git config core.editor`.

At the moment, this gets me about halfway there: when I `git commit`, I get a native NeoVim window wherein I can edit the message. With the recent README update to suggest `:w | bd`, I'm getting even closer! However, I'm still left with the major problem that then I have to go diving into advanced (well, for me 🤣) Vim commands to hunt down the now-missing `:terminal` window that got replaced by the editor.

I'm aware of `-l`, but I don't want to replace any *other* windows in my session — replacing the `:terminal` window *does* seem like the best behaviour — but how on earth do I ensure that I get it *back* once I'm done editing whatever I opened from within it?

(I feel like at least one really basic task like this should be thoroughly and beginner-friendly-ily(?) documented in the README; while I'm sure you don't want to get into the business of teaching people to use Vim, it'd really help to have some pointers!)

**Comment by mhinz** [comment]
First off, I just tried it, and `core.editor` takes precedence over `$VISUAL`, so the `-cc split` isn't used.

That means, that `git commit` in a `:terminal` open a new buffer for the commit message in the _current_ window. After a `w | bd`, you should return to the terminal buffer automatically.

I guess your issue is that your opened the terminal buffer in a new window already, right? So the final `:bd` closes the window and you return to the first window that doesn't show the terminal buffer. Correct?

In that case, I just learned that `$GIT_EDITOR` exists as well. Put this in your vimrc instead:

```vim
if has('nvim')
  let $GIT_EDITOR = 'nvr -cc split --remote-wait'
endif
```

Now, no matter how many windows are opened already, `git commit` in a terminal buffer will open another new window. Then, `:w | bd` should take you to the former window which should show the terminal buffer.

An alternative would be using my https://github.com/mhinz/vim-sayonara. `:Sayonara!` deletes the current buffer but it doesn't close the current window like `:bd` does.

Does this help?

**Comment by ELLIOTTCABLE** [comment]
I'm super-confused by this statement:

> After a `w | bd`, you should return to the terminal buffer automatically.

Er — that's not happening for me? With the configuration from the README, `nvr -s --remote-wait-silent`, followed by a `w | bd`, the window is hosting the newly-opened `COMMIT_EDITMSG` is written, and the buffer in question is deleted, which *closes* the window — it doesn't flip back to displaying a previous buffer, i.e. the `:terminal` buffer (which is now hidden in the background). Do I have a configuration setting somewhere that I've forgotten about that that causes that beaviour? I thought it was the default. 🤣

Meanwhile, what I've started using instead is basically what you mention above: `git config --global core.editor "nvr -s -cc split --remote-wait-silent"`. It handles both being invoked from a `:terminal` buffer *and* from a separate Terminal application quite well (splitting the existing `:terminal` window in the former case, and opening a new `nvim` in the latter case.) So, basically what you suggested as №. 1, but via `git config` instead of Vim's own. (Need to test that `$VISUAL` setup with another command that opens the editor, but can't think of one right this second …)

One thing I ran into with this setup (which is maybe what should be suggested in the README? I, at least, found it a lot more intuitive with the `-cc split`?), is that in the latter case above — when it opens a terminal-nvim session for me — it leaves the original buffer open above the Git buffer, due to the split. I can probably configure this by removing my `core.editor`, and doing some `$GIT_EDITOR` modifications between my `~/.profile` and `~/.vimrc`; but maybe it's worthwhile to support running different commands depending on whether a new process was started or not? idk, just a thought!

**Comment by mhinz** [comment]
I changed the README a few days back. It now suggests

```vim
if has('nvim')
  let $GIT_EDITOR = 'nvr -cc split --remote-wait'
endif
```

and optionally also

```
$ git config --global core.editor 'nvr --remote-wait-silent'
```

This way you get a new window from within `:terminal`, but not from a regular shell.

The core problem here is that `:bdelete` always also deletes the window, which is something I never understood. Hence vim-sayonara. :)

**Comment by TheMeaningfulEngineer** [comment]
Hi there,
so what actually happens when you do `:wq` on the git commit window while having:

```
if has('nvim')
  let $GIT_EDITOR = 'nvr -cc split --remote-wait'
endif
```
in place?
Isn't the `git commit` prompt just a temp file so is should just save and quit with `wq`?

![peek 2019-01-24 20-50](https://user-images.githubusercontent.com/1640260/51704738-111f1900-201a-11e9-91ac-c2d41be32987.gif)

Seem like something is keeping it blocked?

**Comment by TheMeaningfulEngineer** [comment]
@ELLIOTTCABLE (meta) Was that a reply from a mail message? The message seems to have a lot of other stuff :)

> It won’t work until Vim *deletes the buffer*. `:wq` won’t do this, but the
README mentions that you need to `:w | bd` (`:help bd`) instead.

Right. 
All clear on why `wc` doesn't work in this situation. 
Well.... almost all clear :)

The reference explanation I shared states:
> if you have more windows opened (splits): it closes the current window without deleting the buffer. You can see the buffer by :ls

This seems to have a prerequisite on having `set hidden` otherwise the buffer has nowhere to go once you kill it's window.

I've just tried this example again with `set hidden!` in `init.vim` but the behavior is the same.

![peek 2019-01-25 10-44](https://user-images.githubusercontent.com/1640260/51738229-ea4efa00-208e-11e9-9941-6009523e77c2.gif)

Any suggestions on how to explain that?

**Comment by mhinz** [comment]
Explain what exactly? `set hidden!` means `set hidden`. You just close the window, but the buffer is still _loaded_ and in the buffer list. It's just not _active_ (currently shown in any window).

With `set nohidden`, the buffer becomes _unloaded_, but is still in the buffer list (`ls`).

BTW, another thing that just came to my mind:

```vim
autocmd FileType gitcommit set bufhidden=wipe
```

Now, a simple `:x` or `:wq` should make nvr return as well (no `:bd` needed anymore).

**Comment by TheMeaningfulEngineer** [comment]
> `set hidden!` means `set hidden`

Thanks, was misinterpreting `set hidden!` = `set nohidden`instead of `change the value to whatever is opposite if current`.

> With set nohidden, the buffer becomes unloaded, but is still in the buffer list (ls).

Oh...
So there is another state also `unloaded but in a buffer list`. 
Thanks, wasn't aware of that.

```
BTW, another thing that just came to my mind:

autocmd FileType gitcommit set bufhidden=wipe
Now, a simple :x or :wq should make nvr return as well (no :bd needed anymore).
```

This works fabulous, thanks. :+1: 
I don't use a flow with hidden buffers so it's much more intuitive not have to separate the concept
of a buffer and a window when having a single buffer tied to a single window.

**Comment by TheMeaningfulEngineer** [comment]
Hey,
seems that the workaround isn't working for doing `git rebase -i`.
It involves two temporary files, the first one works ok, but it blocks again for the second one.

**Comment by javiertury** [comment]
@TheMeaningfulEngineer, try this

```
autocmd FileType gitcommit,gitrebase,gitconfig,gitsendmail set bufhidden=delete
```
